workflows:
  android-debug-apk:
    name: Central de Campanhas - APK
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      java: 17
    scripts:
      - name: Permitir execução do Gradle Wrapper
        script: chmod +x ./gradlew

      - name: Configurar Android SDK
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Gerar APK de teste
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/outputs/**/*.apk
